# Generated by Django 2.2.5 on 2019-09-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190904_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='has_lost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='has_won',
            field=models.BooleanField(default=False),
        ),
    ]
