# Generated by Django 2.2.5 on 2019-09-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_mines_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='mines_left',
            new_name='flags_left',
        ),
    ]
