# Generated by Django 2.2.5 on 2019-09-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20190904_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='nearby_mines',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
